### ISSUE TITLE
Temperature anomalies on the MKR1500 NB

### ISSUE THREAD

**Issue by strefli3** [ElectronicCats/ElectronicCats_InternalTemperatureZero#11] opened 2024-09-23 14:43 UTC
As seen in the following screen shot I am seeing some anomalies when polling the MKR1500 NB every 15 minutes.

![uTemp](https://github.com/user-attachments/assets/63d60115-9005-4960-b383-f1d028f339e4)

I specified 

```
#define TZ_WITH_DEBUG_CODE
```

But it did not include an additional information in my terminal.

There is a possibility that there is correlation between CPU load and these temperature events, but that is to be decided after more data is collected.

**Comment by xpeqex** [comment] 2024-09-23 15:48
Hey @strefli3!

Thank you for reporting this. I would need to test this on my end, any specific setup you have for testing this?

Also, we will be waiting for your updates.

**Comment by strefli3** [comment] 2024-09-23 16:28
The setup includes reading a few sensors, packaging them in json, and sending them over cellular to an MQTT broker.  Most of the time it works per design. 

On occasion the cellular modem is unable to connect to the network and a watchdog (WTZero) comes in and resets the device. Every temperature anomaly corresponds to the data point after a reset. But not every reset corresponds to an anomaly.  I suspect that the entire board heats up when the cellular model fails to connect - but that is just a hunch.  

Should TZ_WITH_DEBUG_CODE dump more information to  serial, or am I misreading the code?

**Comment by xpeqex** [comment] 2024-09-23 17:20
Thank you for the info. I will try to replicate it on my end with a MKR NB 1500 as well. Also, try testing the library and the board with a simpler code to isolate the use of the library.

About the debug, you should be able to read in the serial monitor different temperature calculations and calibration parameters.
https://github.com/ElectronicCats/ElectronicCats_InternalTemperatureZero/blob/06102dcaa0e4f23dcf4239ec2ef6ff7bdbac0ddd/src/TemperatureZero.cpp#L48-L74

**Comment by strefli3** [comment] 2024-09-26 04:25
Well, I don't believe the ambient temperature of the device itself is the root cause of the problem. I've placed a heat gun pointed at the PCB and the results do not show any anomalies:

![image](https://github.com/user-attachments/assets/b8d5a70e-e208-4161-b094-70a116740f85)


For what it is worth here is the debug information at room temperature, and elevated temperature.

```
01:59:04.830 > +++ Temperature calculation (S):
01:59:04.830 > raw adc reading : 2797
01:59:04.830 > Course temperature : 31.1
01:59:04.830 > Estimated 1V ref @Course temperature : 0.9971
01:59:04.830 > Temperature compensated measurement voltage : 0.6810
01:59:04.831 > Refined temperature : 30.2
```

```
21:07:05.871 > +++ Temperature calculation (S):
21:07:05.871 > raw adc reading : 3011
21:07:05.871 > Course temperature : 53.2
21:07:05.871 > Estimated 1V ref @Course temperature : 0.9983
21:07:05.871 > Temperature compensated measurement voltage : 0.7340
21:07:05.871 > Refined temperature : 52.6
```

I'll keep this running and outputting to the serial port for the time being.

**Comment by xpeqex** [comment] 2024-09-26 15:11
Thank you for sharing your results, they look quite expected and without unexpected behaviors. It is highly probably that the rest of the original code you were using was interfering on the temperature sensor reading on the SAMD21.

Let us know if there are any other questions!

**Comment by strefli3** [comment] 2024-09-26 15:50
All the code remains the same with the exception of the debug printing (and having usb plugged in). I'll continue to run tests to see if the problem reoccurs.

**Comment by strefli3** [comment] 2024-09-27 01:05
At last.  Notice the `08:53:05.959 > BARK! BARK! BARK!` which is my indicator that the watch dog fired and forced a reset.

```
08:22:30.670 > +++ Temperature calculation (S):
08:22:30.670 > raw adc reading : 2776
08:22:30.670 > Course temperature : 28.9
08:22:30.670 > Estimated 1V ref @Course temperature : 0.9969
08:22:30.670 > Temperature compensated measurement voltage : 0.6758
08:22:30.671 > Refined temperature : 28.0
08:22:37.723 > *** Publishing message
08:22:37.723 >
08:22:39.110 > Disconnecting from MQTT...
08:22:50.324 > Free memory: 4959 bytes
08:22:50.331 > Duration was...55890ms
08:22:50.331 > Sleeping...14.07 minutes
08:22:50.331 > ************************
08:22:50.331 > **** Going to Sleep ****
08:22:50.331 > ************************
08:37:13.480 > Verifying connection...
08:37:13.491 > Connection verification start...
08:37:13.491 > Attempting to connect to the cellular network
08:37:27.161 > You're connected to the cellular network
08:37:27.161 > 
08:37:35.456 > You're connected to the MQTT broker
08:37:35.484 > Connection verification complete
08:37:43.528 > 
08:37:43.528 > +++ Temperature calculation (S):
08:37:43.528 > raw adc reading : 2777
08:37:43.528 > Course temperature : 29.0
08:37:43.528 > Estimated 1V ref @Course temperature : 0.9969
08:37:43.529 > Temperature compensated measurement voltage : 0.6761
08:37:43.529 > Refined temperature : 28.1
08:37:50.595 > *** Publishing message
08:37:50.595 > 
08:37:51.925 > Disconnecting from MQTT...
08:38:03.146 > Free memory: 4959 bytes
08:38:03.151 > Duration was...53710ms
08:38:03.151 > Sleeping...14.10 minutes
08:38:03.152 > ************************
08:38:03.152 > **** Going to Sleep ****
08:38:03.152 > ************************
08:52:28.469 > Verifying connection...
08:52:28.470 > Connection verification start...
08:52:28.470 > Attempting to connect to the cellular network
08:52:42.559 > You're connected to the cellular network
08:52:42.559 > 
08:52:50.836 > You're connected to the MQTT broker
08:52:50.855 > Connection verification complete
08:52:58.909 > 
08:52:58.909 > +++ Temperature calculation (S):
08:52:58.909 > raw adc reading : 2777
08:52:58.909 > Course temperature : 29.0
08:52:58.909 > Estimated 1V ref @Course temperature : 0.9969
08:52:58.909 > Temperature compensated measurement voltage : 0.6761
08:52:58.909 > Refined temperature : 28.1
08:53:05.959 > *** Publishing message
08:53:05.959 > BARK! BARK! BARK!
08:56:55.166 > Serial started!
08:56:55.177 > **************************************
08:56:55.177 > ****** Init Start Version 0.1.0 ******
08:56:55.177 > **************************************
08:56:55.177 > init TempZero...
08:56:55.177 > Calibration:
08:56:55.177 > 
08:56:55.177 > +++ Factory calibration parameters:
08:56:55.177 > Room Temperature : 30.0
08:56:55.177 > Hot Temperature  : 85.0
08:56:55.177 > Room Reading     : 2795
08:56:55.177 > Hot Reading      : 3319
08:56:55.177 > Room Voltage ref raw / interpreted : 3 / 0.9970
08:56:55.177 > Hot Voltage ref raw / interpreted  : 0 / 1.0000
08:56:55.177 > Room Reading compensated : 0.6805
08:56:55.177 > Hot Reading compensated  : 0.8105
08:56:55.177 > Blinking LED 2 times...
08:56:59.266 > Blinking LED 4 times...
08:57:06.264 > LIDAR Firmware version: 
08:57:06.765 > 2.1.5
08:57:06.765 > Data-Frame rate: 20Hz
08:57:12.268 > Blinking LED 6 times...
08:57:23.422 > Current carrier: Project Fi
08:57:23.444 > Signal Strength: 25 [0-31]
08:57:23.471 > Blinking LED 8 times...
08:57:28.472 > Blinking LED 25 times...
08:57:31.528 > ************************
08:57:31.528 > **** Init Complete! ****
08:57:31.528 > ************************
08:57:31.528 > ************************
08:57:31.528 > ****** Loop Start ******
08:57:31.528 > ************************
08:57:34.548 > Verifying connection...
08:57:34.548 > Connection verification start...
08:57:34.548 > Attempting to connect to the cellular network
08:57:48.458 > You're connected to the cellular network
08:57:48.458 > 
08:57:51.468 > Attempting to connect to MQTT broker: a1on0hlcugt2vg-ats.iot.us-west-2.amazonaws.com 
08:57:56.733 > You're connected to the MQTT broker
08:57:56.760 > Connection verification complete
08:58:03.791 > +++ Temperature calculation (S):
08:58:03.791 > raw adc reading : 2325
08:58:03.791 > Course temperature : -17.7
08:58:03.791 > Estimated 1V ref @Course temperature : 0.9944
08:58:03.792 > Temperature compensated measurement voltage : 0.5646
08:58:03.792 > Refined temperature : -19.0
08:58:10.840 > *** Publishing message
08:58:12.211 > Disconnecting from MQTT...
08:58:13.960 > Free memory: 5107 bytes
08:58:13.960 > Duration was...42429ms
08:58:13.960 > Sleeping...14.29 minutes
08:58:13.960 > ************************
08:58:13.960 > **** Going to Sleep ****
08:58:13.960 > ************************
09:12:31.961 > 
09:12:31.961 > ****** Loop Start ******
09:12:31.961 > ************************
09:12:35.981 > Verifying connection...
09:12:35.981 > Connection verification start...
09:12:35.981 > Attempting to connect to the cellular network
09:12:50.826 > You're connected to the cellular network
09:12:50.826 > 
09:12:58.914 > You're connected to the MQTT broker
09:12:58.930 > Connection verification complete
09:13:06.981 > +++ Temperature calculation (S):
09:13:06.982 > raw adc reading : 2776
09:13:06.982 > Course temperature : 28.9
09:13:06.982 > Estimated 1V ref @Course temperature : 0.9969
09:13:06.982 > Temperature compensated measurement voltage : 0.6758
09:13:06.982 > Refined temperature : 28.0
```

**Comment by xpeqex** [comment] 2024-09-27 18:54
The output looks very consistent until the watchdog kicks, then the first readings shows erratic readings. 

I have tried replicating this on my end, but I used a simpler code without MQTT features. The results were positive, consistent readings after the watchdog (WDTZero) kicking in. The only problem I faced was the port number assignation, but this is a port assignation issue related to the operative system.

Here are some possible causes to the erratic issues you are facing:

- **ADC Reading Fluctuations:** Variations in the ADC readings can occur due to noise or fluctuations in the power supply. Ensure that your power supply is stable
- **Problems with the code, memory leaks or limitations:** I recommend isolating the use of the library to a simpler use, then continue adding other libraries or functions to identify the cause.

**Comment by xpeqex** [comment] 2024-09-30 17:16
We have concluded that the issue may be related to the setup instead of the library, so we will close this ticket. If you have any other queries feel free to open a new issue.

**Closed as completed by xpeqex** 2024-09-30 17:16 UTC
Labels: Help wanted, Question a/Library

**Comment by strefli3** [comment] 2024-11-09 04:19
After an additional month of testing and debugging I can confirm that the problem was due to what I assume is a memory leak (or some other deficiency) in the Arduino ArduinoMqttClient. Once I stopped using MQTT in favor for HTTP the code and hardware have been much better behaved.

Thanks for the help!

![image](https://github.com/user-attachments/assets/076cb361-e0f1-4037-9599-19268005892f)

**Comment by xpeqex** [comment] 2024-11-11 16:07
Thank you for the update! I'm glad you found a solution to this issue.
